### ISSUE TITLE
Fails to build with JDBC 9.4 (PGObject class removed)

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#5438]
**[Submitted to the original trac issue database at 8.30pm, Wednesday, 11th January 2017]**

The PGHStore class causes a build failure with the latest PostgreSQL JDBC driver (9.4-1212) as reported by Lucas Nussbaum in [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850993 Debian Bug #850993]:
> ```
> /<<PKGBUILDDIR>>/osmosis-hstore-jdbc/src/main/java/org/openstreetmap/osmosis/hstore/PGHStore.java:36: error: package org.postgresql.util does not exist
> import org.postgresql.util.PGobject;
>                           ^
> /<<PKGBUILDDIR>>/osmosis-hstore-jdbc/src/main/java/org/openstreetmap/osmosis/hstore/PGHStore.java:42: error: cannot find symbol
> public class PGHStore extends PGobject implements Serializable, Cloneable, Map<String, String>
>                               ^
>   symbol: class PGobject
> /<<PKGBUILDDIR>>/osmosis-hstore-jdbc/src/main/java/org/openstreetmap/osmosis/hstore/PGHStore.java:52: error: cannot find symbol
>         setType("hstore");
>         ^
>   symbol:   method setType(String)
>   location: class PGHStore
> 3 errors
> 1 warning
> :osmosis-hstore-jdbc:compileJava FAILED
> ```

This issue will cause the removal of the osmosis package from the upcoming Debian stable release (stretch).

**Comment by tomhughes** [comment]
**Author: sebastic**
**[Added to the original trac issue at 9.37pm, Wednesday, 11th January 2017]**

Sorry for the noise, this was a false positive. I overlooked the groupId change in the updated postgresql-jdbc package which was the cause for the PGobject class not being found.
